apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-vultr
  namespace: kube-system
type: Opaque
stringData:
  token: << VULTR_TOKEN >>
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: vultr-machinedeployment
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
          cloudProvider: "vultr"
          cloudProviderSpec:
            token:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-vultr
                key: token

            machineType: "cloud-instance"
            region: "ams"
            plan: "vbm-4c-32gb"
            tags:
              - your
              - tags
              - here

          operatingSystem: "ubuntu"
          operatingSystemSpec:
            distUpgradeOnBoot: true
      versions:
        kubelet: 1.22.5
